name: "Andrea Ricolfi"
url: atricolfi.github.io
description: ATR

permalink: /themes/:title/

gems: [jekyll-paginate]

rouge: pygments
paginate: 20

markdown: rdiscount
rdiscount:
    extensions: ['smart']

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile', 'vendor']
